### ISSUE TITLE
[Feature Request] Linking Macros to Hotbars

### ISSUE THREAD

**Issue by JustForFF** [grittyfrog/MacroMate#12]
Hi again!

I was just wondering if it's possible to link Macros to specific slots on Hotbar slots in a similar fashion to how you can link Macros to Macro slots? I use a decent amount of Macros to simply just track my bigger CDs (Think something like Arcane Circle) or Shorter CDs I should to use, (think of things like Gluttony and Soul Slice) and I put all these as Macros on Bigger Higher up Bars so I don't strain myself looking down. However, as I open up the amount of classes I am using, I am encountering more and more difficulty keeping all of them, slowly pruning away stuff I don't "fully need".

MM allows me to pretty much save all the macros, and if I go "full in" on a class I like enough, they're there and I don't need to worry, only thing that is a bit troubling is swapping them over from the User Macro menu to my bigger higher up hotbars, I understand it may be out of scope and it is a bit of a big ask, but I thought maybe it's more easily possible because this plugin does have the ability to link to the User Macro menu already so, worth the ask so I know if it's possible or not!

Thanks in advance to any response and thank you so much for the plugin as is🙏

**Comment by grittyfrog** [comment]
I'd love to be able to do this, but directly binding to the hotbar is not something I can support. 

To the best of my knowledge no plugin does it because the hotbar is a very sensitive part of the game, and there isn't any known way to create a "fake" hotbar binding that isn't to a real action or macro.

Thanks for the suggestion regardless :slightly_smiling_face:
